spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.testcross.testcrossblog.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
